version: '2'

services:
  lambda:
    container_name: lambda
    image: lambci/lambda:python3.6
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    volumes:
      - .:/var/task
